import Head from 'next/head'
import Main from '../components/Main'

type Props = {
  title: string
}

export default function Home({ title = 'React Avançado' }: Props) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2> Body </h2>
        <Main />
      </main>

      <footer>
        <h2> Footer </h2>
      </footer>
    </div>
  )
}
